import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function BuffPups() {
  return (
    <section id="page">
      <Head>
        <title>
          BUFF PUPS &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="BUFF PUPS &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/buff-pups" />
        <meta
          itemProp="name"
          content="BUFF PUPS — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/buff-pups" />
        <meta
          name="twitter:title"
          content="BUFF PUPS — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/buff-pups" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/buff-pups/buff-pups-1.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-2.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-3.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-4.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-5.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-6.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-7.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-8.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-9.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-10.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-11.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-12.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-13.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-14.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-15.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-16.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-17.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-18.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-19.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-20.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-21.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-22.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-23.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-24.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-25.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-26.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-27.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-28.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-29.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-30.jpg',
          },
          {
            src:
              '/assets/images/buff-pups/buff-pups-32.jpg',
          },
		    {
            src:
              '/assets/images/buff-pups/buff-pups-33.jpg',
          },
        ]}
      />
    </section>
  )
}
