import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function Butter() {
  return (
    <section id="page">
      <Head>
        <title>
          BUTTER &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="BUTTER &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/butter" />
        <meta
          itemProp="name"
          content="BUTTER — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/butter" />
        <meta
          name="twitter:title"
          content="BUTTER — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/butter" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/butter/butter-1.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-2.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-3.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-4.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-5.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-6.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-7.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-8.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-9.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-10.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-11.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-12.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-13.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-14.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-15.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-16.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-17.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-18.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-19.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-20.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-21.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-22.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-23.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-24.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-25.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-26.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-27.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-28.JPG',
          },
		    {
            src:
              '/assets/images/butter/butter-29.JPG',
          },
          {
            src:
              '/assets/images/butter/butter-30.JPG',
          },
      
        ]}
      />
    </section>
  )
}
