import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function Butter() {
  return (
    <section id="page">
      <Head>
        <title>
          BUTTER &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="BUTTER &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/butter" />
        <meta
          itemProp="name"
          content="BUTTER — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/butter" />
        <meta
          name="twitter:title"
          content="BUTTER — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/butter" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/butter/butter-1.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-2.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-3.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-4.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-5.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-6.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-7.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-8.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-9.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-10.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-11.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-12.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-13.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-14.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-15.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-16.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-17.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-18.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-19.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-20.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-21.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-22.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-23.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-24.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-25.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-26.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-27.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-28.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-29.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-30.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-32.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-33.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-34.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-35.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-36.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-37.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-38.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-39.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-40.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-41.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-42.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-43.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-45.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-46.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-47.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-48.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-49.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-50.jpg',
          },
		    {
            src:
              '/assets/images/butter/butter-51.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-52.jpg',
          },
          {
            src:
              '/assets/images/butter/butter-53.jpg',
          },
        ]}
      />
    </section>
  )
}
