import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function Deadlift() {
  return (
    <section id="page">
      <Head>
        <title>
          DEADLIFT &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="DEADLIFT &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/deadlift" />
        <meta
          itemProp="name"
          content="DEADLIFT — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/deadlift" />
        <meta
          name="twitter:title"
          content="DEADLIFT — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/deadlift" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/deadlift/deadlift-1.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-2.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-3.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-4.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-5.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-6.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-7.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-8.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-9.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-10.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-11.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-12.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-13.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-14.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-15.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-16.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-17.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-18.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-19.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-20.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-21.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-22.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-23.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-24.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-25.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-26.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-27.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-28.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-29.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-30.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-32.jpg',
          },
		    {
            src:
              '/assets/images/deadlift/deadlift-33.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-34.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-35.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-36.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-37.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-38.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-39.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-40.jpg',
          },
          {
            src:
              '/assets/images/deadlift/deadlift-41.jpg',
          },
        
        ]}
      />
    </section>
  )
}
