import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function GirlFriend() {
  return (
    <section id="page">
      <Head>
        <title>
          GIRLFRIEND &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="GIRLFRIEND &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/girlfriend" />
        <meta
          itemProp="name"
          content="GIRLFRIEND — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/girlfriend" />
        <meta
          name="twitter:title"
          content="GIRLFRIEND — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/girlfriend" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/girlfriend/girlfriend-1.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-2.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-3.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-4.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-5.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-6.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-7.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-8.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-9.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-10.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-11.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-12.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-13.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-14.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-15.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-16.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-17.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-18.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-19.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-20.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-21.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-22.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-23.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-24.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-25.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-26.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-27.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-28.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-29.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-30.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-32.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-33.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-34.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-35.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-36.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-37.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-38.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-39.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-40.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-41.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-42.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-43.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-45.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-46.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-47.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-48.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-49.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-50.jpg',
          },
		    {
            src:
              '/assets/images/girlfriend/girlfriend-51.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-52.jpg',
          },
          {
            src:
              '/assets/images/girlfriend/girlfriend-53.jpg',
          },
        ]}
      />
    </section>
  )
}
