import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function HandBags() {
  return (
    <section id="page">
      <Head>
        <title>
          HANDBAGS &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="HANDBAGS &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/handbags" />
        <meta
          itemProp="name"
          content="HANDBAGS — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/handbags" />
        <meta
          name="twitter:title"
          content="HANDBAGS — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/handbags" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/handbags/handbags-1.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-2.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-3.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-4.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-5.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-6.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-7.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-8.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-9.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-10.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-11.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-12.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-13.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-14.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-15.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-16.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-17.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-18.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-19.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-20.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-21.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-22.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-23.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-24.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-25.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-26.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-27.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-28.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-29.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-30.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-32.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-33.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-34.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-35.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-36.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-37.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-38.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-39.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-40.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-41.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-42.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-43.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-45.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-46.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-47.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-48.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-49.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-50.jpg',
          },
		    {
            src:
              '/assets/images/handbags/handbags-51.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-52.jpg',
          },
          {
            src:
              '/assets/images/handbags/handbags-53.jpg',
          },
        ]}
      />
    </section>
  )
}
