import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function Juicy() {
  return (
    <section id="page">
      <Head>
        <title>
          JUICY &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="JUICY &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/juicy" />
        <meta
          itemProp="name"
          content="JUICY — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/juicy" />
        <meta
          name="twitter:title"
          content="JUICY — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/juicy" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/juicy/juicy-1.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-2.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-3.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-4.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-5.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-6.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-7.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-8.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-9.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-10.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-11.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-12.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-13.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-14.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-15.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-16.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-17.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-18.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-19.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-20.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-21.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-22.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-23.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-24.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-25.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-26.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-27.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-28.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-29.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-30.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-32.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-33.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-34.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-35.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-36.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-37.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-38.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-39.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-40.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-41.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-42.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-43.jpg',
          },
		    {
            src:
              '/assets/images/juicy/juicy-45.jpg',
          },
          {
            src:
              '/assets/images/juicy/juicy-46.jpg',
          },
 
        ]}
      />
    </section>
  )
}
