import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function NoFilter() {
  return (
    <section id="page">
      <Head>
        <title>
          NO FILTER &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="NO FILTER &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/no-filter" />
        <meta
          itemProp="name"
          content="NO FILTER — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/no-filter" />
        <meta
          name="twitter:title"
          content="NO FILTER — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/no-filter" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/no-filter/no-filter-1.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-2.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-3.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-4.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-5.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-6.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-7.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-8.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-9.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-10.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-11.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-12.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-13.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-14.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-15.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-16.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-17.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-18.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-19.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-20.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-21.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-22.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-23.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-24.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-25.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-26.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-27.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-28.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-29.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-30.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-32.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-33.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-34.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-35.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-36.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-37.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-38.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-39.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-40.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-41.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-42.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-43.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-45.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-46.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-47.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-48.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-49.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-50.jpg',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-51.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-52.jpg',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-53.jpg',
          },
        ]}
      />
    </section>
  )
}
