import Head from 'next/head'
import CustomPage from '../components/custom-page/custom-page'

export default function NoFilter() {
  return (
    <section id="page">
      <Head>
        <title>
          NO FILTER &mdash; Lindsey Carrillo Design Portfolio
        </title>
        <meta
          property="og:title"
          content="NO FILTER &mdash; Lindsey Carrillo Design Portfolio"
        />
        <meta property="og:url" content="/no-filter" />
        <meta
          itemProp="name"
          content="NO FILTER — Lindsey Carrillo Design Portfolio"
        />
        <meta itemProp="url" content="/no-filter" />
        <meta
          name="twitter:title"
          content="NO FILTER — Lindsey Carrillo Design Portfolio"
        />
        <meta name="twitter:url" content="/no-filter" />
      </Head>
      <CustomPage
        imageList={[
          {
            src:
              '/assets/images/no-filter/no-filter-1.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-2.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-3.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-4.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-5.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-6.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-7.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-8.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-9.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-10.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-11.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-12.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-13.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-14.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-15.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-16.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-17.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-18.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-19.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-20.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-21.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-22.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-23.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-24.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-25.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-26.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-27.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-28.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-29.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-30.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-32.JPG',
          },
		    {
            src:
              '/assets/images/no-filter/no-filter-33.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-34.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-35.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-36.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-37.JPG',
          },
          {
            src:
              '/assets/images/no-filter/no-filter-38.JPG',
          },

        ]}
      />
    </section>
  )
}
